# Generated by Django 5.2.2 on 2025-08-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'register_student',
            },
        ),
    ]
