# Generated by Django 5.2.2 on 2025-09-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('status', models.CharField(choices=[('passed', 'Đã hoàn thành'), ('studying', 'Đang học'), ('not_started', 'Chưa học')], max_length=50)),
                ('register_status', models.CharField(choices=[('registered', 'Đã đăng ký'), ('not_register', 'Chưa đăng ký')], max_length=50)),
            ],
            options={
                'db_table': 'course_module',
            },
        ),
        migrations.CreateModel(
            name='RecommendCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
                ('status', models.CharField(choices=[('passed', 'Đã hoàn thành'), ('studying', 'Đang học'), ('not_started', 'Chưa học')], max_length=50)),
            ],
            options={
                'db_table': 'mycourse',
            },
        ),
        migrations.CreateModel(
            name='RecommendDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, max_length=1024, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('source_id', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=512, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recommend_book',
            },
        ),
        migrations.CreateModel(
            name='StudentsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.IntegerField()),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job', models.CharField(max_length=50)),
                ('other', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'account_students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='ListLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lessons_videos/')),
                ('course', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='home.coursemodule')),
            ],
            options={
                'db_table': 'list_lesson',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('play', 'Play video'), ('pause', 'Pause video'), ('back', 'Back to list'), ('done', 'Mark as done')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentsaccount', to_field='student_id')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.listlesson')),
            ],
            options={
                'db_table': 'user_action',
            },
        ),
    ]
